name: angel3_mongo
version: 8.2.0
description: MongoDB-enabled services for the Angel3 framework. Well-tested.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/mongo
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  angel3_framework: ^8.0.0
  angel3_container: ^8.0.0
  belatuk_json_serializer: ^7.1.0
  belatuk_merge_map: ^5.1.0
  mongo_dart: ^0.10.3
dev_dependencies:
  http: ^1.0.0
  test: ^1.24.0
  lints: ^4.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request